name: Call Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get Action 
        id: foo
        uses:  TeddyBrod/Composite-action@main
        with:
          who-to-greet: "Fred"
          duck_token: ${{ secrets.DUCK_TOKEN }}
          
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      

