name: Call workflow

on:
  workflow_call:
   secrets:
    DUCK_TOKEN:
     required: true
     
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get Action 
        id: foo
        uses:  TeddyBrod/Composite-action@main
        with:
          who-to-greet: "Fred"
          duck_token: ${{ inputs.DUCK_TOKEN }}
  
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: cat name.txt
