name: Call workflow

on:
  workflow_call:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: foo
        uses:  TeddyBrod/Composite-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: cat name.txt
